// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/chat.proto

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	ChatInitiate(ctx context.Context, in *InitiateRequest, opts ...grpc.CallOption) (*InitiateResponse, error)
	SendMessage(ctx context.Context, in *MessageReuquest, opts ...grpc.CallOption) (*empty.Empty, error)
	UserStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (ChatService_UserStreamClient, error)
	ChastStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (ChatService_ChastStreamClient, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) ChatInitiate(ctx context.Context, in *InitiateRequest, opts ...grpc.CallOption) (*InitiateResponse, error) {
	out := new(InitiateResponse)
	err := c.cc.Invoke(ctx, "/chat.ChatService/ChatInitiate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SendMessage(ctx context.Context, in *MessageReuquest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/chat.ChatService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UserStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (ChatService_UserStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], "/chat.ChatService/UserStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceUserStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_UserStreamClient interface {
	Recv() (*UserStreamResponse, error)
	grpc.ClientStream
}

type chatServiceUserStreamClient struct {
	grpc.ClientStream
}

func (x *chatServiceUserStreamClient) Recv() (*UserStreamResponse, error) {
	m := new(UserStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) ChastStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (ChatService_ChastStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[1], "/chat.ChatService/ChastStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceChastStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_ChastStreamClient interface {
	Recv() (*StreamMessage, error)
	grpc.ClientStream
}

type chatServiceChastStreamClient struct {
	grpc.ClientStream
}

func (x *chatServiceChastStreamClient) Recv() (*StreamMessage, error) {
	m := new(StreamMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility
type ChatServiceServer interface {
	ChatInitiate(context.Context, *InitiateRequest) (*InitiateResponse, error)
	SendMessage(context.Context, *MessageReuquest) (*empty.Empty, error)
	UserStream(*StreamRequest, ChatService_UserStreamServer) error
	ChastStream(*StreamRequest, ChatService_ChastStreamServer) error
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (UnimplementedChatServiceServer) ChatInitiate(context.Context, *InitiateRequest) (*InitiateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatInitiate not implemented")
}
func (UnimplementedChatServiceServer) SendMessage(context.Context, *MessageReuquest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatServiceServer) UserStream(*StreamRequest, ChatService_UserStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method UserStream not implemented")
}
func (UnimplementedChatServiceServer) ChastStream(*StreamRequest, ChatService_ChastStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ChastStream not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_ChatInitiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ChatInitiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/ChatInitiate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ChatInitiate(ctx, req.(*InitiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageReuquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendMessage(ctx, req.(*MessageReuquest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UserStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).UserStream(m, &chatServiceUserStreamServer{stream})
}

type ChatService_UserStreamServer interface {
	Send(*UserStreamResponse) error
	grpc.ServerStream
}

type chatServiceUserStreamServer struct {
	grpc.ServerStream
}

func (x *chatServiceUserStreamServer) Send(m *UserStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatService_ChastStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).ChastStream(m, &chatServiceChastStreamServer{stream})
}

type ChatService_ChastStreamServer interface {
	Send(*StreamMessage) error
	grpc.ServerStream
}

type chatServiceChastStreamServer struct {
	grpc.ServerStream
}

func (x *chatServiceChastStreamServer) Send(m *StreamMessage) error {
	return x.ServerStream.SendMsg(m)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatInitiate",
			Handler:    _ChatService_ChatInitiate_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChatService_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UserStream",
			Handler:       _ChatService_UserStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ChastStream",
			Handler:       _ChatService_ChastStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/chat.proto",
}
